### ISSUE TITLE
Bower Incompatibility

### ISSUE THREAD

**Issue by aweebs** [duongtdvn/uniform#1]
Could you please update your 1.0 release tag to comply with Semantic Versioning that bower uses by adding a patch number?
This would mean changing the v1.0 tag to v1.0.0 or v1.0.1.

Right now when specifying dependencies in my bower.json file I cannot specify a version of jquery-uniform to download, and must use an asterisk. It would be nice to properly specify a version.

Thanks.

**Comment by duongtdvn** [comment]
I have fixed the issue, thank you for reporting (:
